general:
  device: cuda
  device_id: '0'
  work_dir: default
  seed: 42
  deterministic: true
  freeze: []
  unfreeze: []
  ckpt:
    path: ''
    modules:
      from:
      - all
      to:
      - all
  testing_ckpt: default
  train: True
  eval: True

model:
  name: EmotionBaselineModel
  tag: v7
  description: ''
  ssl_model_str: WAVLM_LARGE
  text_model_str: ROBERTA_BASE_ENCODER
  num_classes: 8
  d_model: 512
  d_contrastive: 512
  dropout: 0.5

solver:
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  max_epochs: 20
  freeze_epochs: 0
  lr:
    default: 1e-5
    ssl_model: 1e-6
    text_model: 1e-6
    ser_model: 1e-5
  min_lr:
    default: 1e-6
    ssl_model: 1e-7
    text_model: 1e-7
    ser_model: 1e-6
  iters_to_accumulate: 2
  amp_dtype: fp16
  criterions:
    # ce_loss:
    #   name: CrossEntropyLoss
    #   label_smoothing: 0.1
    #   total_weight: 1.0
    wce_loss:
      name: WeightedCrossEntropyLoss
      weight: 0 #0 means default
      label_smoothing: 0.1
      total_weight: 1.0
    mpcl_loss:
      name: mpcl_loss
      temperature: 0.1
      total_weight: 1.0
    
datasets:
  train_datasets:
  - name: MSP_Podcast
    dir: /home/icebird/01_proj/crab/dataset
  test_datasets:
  - name: MSP_Podcast
    dir: /home/icebird/01_proj/crab/dataset

dataloader:
  name: BalancedLengthSampler
  num_workers: 20
  text_max_len: 128
  # token_batch_size: 80000
  batch_size:
    train: 16
    dev: 16
    eval: 1
linebot:
  enable: false

wandb:
  enable: true
  entity: fcu-slp
  project: crab
