general:
  device: cuda
  device_id: '3'
  work_dir: default
  seed: 39
  deterministic: true
  freeze: []
  unfreeze: []
  ckpt:
    path: ''
    modules:
      from:
      - all
      to:
      - all
  testing_ckpt: default
  train: true
  eval: true
  produce_evaluation_file: true

model:
  name: DeepfakeAudioTextTransformerModel
  tag: v6
  description: 'Baseline for ADD task using Audio and Text'
  ssl_model_str: WAV2VEC2_XLSR_300M
  use_audio: true
  use_rhythm: false
  use_text: true
  num_classes: 2
  d_model: 256
  d_contrastive: 128
  n_heads: 4
  n_transformer_encoder_layers: 1
  dropout: 0.3

solver:
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  max_epochs: 20
  freeze_epochs: 0
  lr:
    default: 0.00001
  iters_to_accumulate: 8
  amp_dtype: fp16
  criterions:
    ce_loss:
      name: CrossEntropyLoss
      label_smoothing: 0.1
      total_weight: 1.0

datasets:
  train_datasets:
  - name: ASVspoof5
    dir: /data/m314832018/Lab8/crab/dataset
    use_duration: true
  test_datasets:
  - name: ASVspoof5
    dir: /data/m314832018/Lab8/crab/dataset
    use_duration: true

dataloader:
  name: Dataset
  num_workers: 8
  batch_size:
    train: 8
    dev: 4
    eval: 4

linebot:
  enable: false

wandb:
  enable: true
  entity: icebird50817
  project: crab
