general:
  device: cuda
  device_id: '0'
  work_dir: default
  seed: 39
  deterministic: true
  freeze: []
  unfreeze: []
  ckpt:
    path: ''
    modules:
      from:
      - all
      to:
      - all
  testing_ckpt: default
  train: True
  eval: True
  produce_evaluation_file: true

model:
  name: DeepfakeCrabModel
  tag: v7
  description: ''
  ssl_model_str: WAV2VEC2_XLSR_300M
  
  d_model: 256
  n_cls_encoder_layers: 4

solver:
  optimizer: AdamW
  scheduler: div
  max_epochs: 32
  freeze_epochs: 0
  lr:
    default: 0.0001
  iters_to_accumulate: 8
  amp_dtype: fp16
  criterions:
    ce_loss:
      name: CrossEntropyLoss
      label_smoothing: 0.1
      total_weight: 1.0

datasets:
  train_datasets:
  - name: ASVspoof5
    # dir: /home/poyu39/gitlab/fcu-slp/ssl-mamba/dataset
    dir: /home/icebird/01_proj/ssl-mamba/dataset
  test_datasets:
  - name: ASVspoof2021_DF
    dir: /home/icebird/01_proj/ssl-mamba/dataset
  - name: ASVspoof2021_LA
    dir: /home/icebird/01_proj/ssl-mamba/dataset

dataloader:
  name: Dataset
  num_workers: 20
  batch_size:
    train: 16
    dev: 32
    eval: 32

linebot:
  enable: false

wandb:
  enable: true
  entity: fcu-slp
  project: ssl-mamba
